// AttractionAction
export const SET_LOADING = "SET_LOADING";
export const SAVE_ALL_ATTRACTIONS = "SAVE_ALL_ATTRACTIONS";
export const ATTRACTION_ADDED = "ATTRACTION_ADDED";
export const ATTRACTION_DELETED = "ATTRACTION_DELETED";
export const ATTRACTION_UPDATED = "ATTRACTION_UPDATED";

// UserActions
export const CURRENT_USER = "CURRENT_USER"

// WishList
export const ADDED_ATTRACTION_TO_WISH_LIST="ADDED_ATTRACTION_TO_WISH_LIST";
export const ATTRACTION_DELETED_FROM_WISH_LIST="ATTRACTION_DELETED_FROM_WISH_LIST";
export const WISH_LIST_ACCEPTED="WISH_LIST_ACCEPTED";

// Order
export const SAVE_ALL_ORDERS = "SAVE_ALL_ORDERS";

// Category
export const SAVE_ALL_CATEGORIES = "SAVE_ALL_CATEGORIES";
export const CATEGORY_ADDED = "CATEGORY_ADDED";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_CHANGED = "CATEGORY_CHANGED";
